# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/msm8998-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter chiron sagit,$(TARGET_DEVICE)),)

endif
